## Copyright (C) 2017 Sebastiano Rusca
## Copyright (C) 2017 Juan Pablo Carbajal
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.

## Author: Sebastiano Rusca
## Created: 2017-12-11

pkg load fswof2d


## Global parameters
#
dataFolder  = "data";
studyName   = "test_Exp01";

## Generate topography
# Exp01 uses a Thacker topography ("TopographyInit = 3")

##
# Domain geometry
Lx    = 6.4;
Ly    = 12.8;

##
# Topography mesh parameters
Nxcell = 32;
Nycell = 64;

## Generate initial conditions
# Exp01 uses h0, v0, u0 = 0 as initial conditions ("huvInit = 2")

## Write out data files
#

# FullSOWF_2D needs an Inputs and Ouput folder, check user manual.
inputsFolder  = fullfile (dataFolder, studyName, 'Inputs');
outputsFolder = fullfile (dataFolder, studyName, 'Outputs');
fname         = @(s) fullfile (inputsFolder, s);
mkdir (inputsFolder);
mkdir (outputsFolder);

# write out topography: performed by FullSWOF_2D -> Thacker topography

# write out IC: file copied from FullSWOF_2D folder into repository.
# The topography cannot be generated by the "fswof2d package", therefore
# IC cannot be written to file with huv2file (function requires xx and yy)

# Initialize the parameters with the values of Exp01
simT      = 50;
nbT       = 2;
friclaw   = 2;
friccoef  = 0.25;
infiltr   = 1;
rain      = 1;
rainfile  = "exp01_rain.txt";
topofile  = "exp01_topography.txt";
huvfile   = "exp01_huv.txt";

params2file ("ParamsFile", fname('parameters.txt'), ...
             "xCells", Nxcell, ...
             "yCells", Nycell, ...
             "xLength", Lx, ...
             "yLength", Ly, ...
             "SimTime", simT, ...
             "SavedTimes", nbT, ...
             "FrictLaw", friclaw, ...
             "FrictCoef", friccoef, ...
             "InfModel", infiltr, ...
             "TopographyFile", topofile, ...
             "huvFile", huvfile, ...
             "RainInit", rain, ...
             "RainFile", rainfile);






