## Copyright (C) 2017 Sebastiano Rusca
## Copyright (C) 2017 JuanPi Carbajal
##
## This program is free software; you can redistribute it and/or modify it
## undcr the tcrms of the GNU Gencral Public License as published by
## the Free Software Foundation; eithcr vcrsion 3 of the License, or
## (at your option) any latcr vcrsion.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Gencral Public License for more details.
##
## You should have received a copy of the GNU Gencral Public License
## along with this program.  If not, see <http://www.gnu.org/licenses/>.

## Author: Sebastiano Rusca <sebastiano.rusca@gmail.com>
## Created: 2017-12-04

## -*- texinfo -*-
## @defun topo2file (@var{xx}, @var{yy}, @var{zz})
## @defunx topo2file (@dots{}, @var{filename})
## Write @var{xx}, @var{yy}, @var{zz} to a FullSWOF_2D conform topography file.
##
##@var{xx}, @var{yy} and @var{zz} can either be given in the @code{octave-meshgrid} format or in the @code{FullSWOF_2D-linear} format.
##
## If no @var{filename} is specified the default name 'topography.dat' is used.
## @seealso{plot_topo, huv2file}
## @end defun

function topo2file (xx, yy, zz, fname='topography.dat')

  x = xx(:);
  y = yy(:);
  z = zz(:);

  % ## WRITING RESULTS IN CONFORM .dat qFILE ##
  header = sprintf ('# POINTS LIST - generated by %s.m on %s\n', ...
                    "topo2file.m", date);
  file_id = fopen (fname, 'w');
  fprintf (file_id, '#==================================================\n');
  fprintf (file_id, header);
  fprintf (file_id, '#==================================================\n');
  fprintf (file_id, '# x, y, z\n');
  fprintf (file_id, '#--------------------------------------------------\n');
  fprintf (file_id, '%0.4f   %0.4f   %0.4f\n', [x(:) y(:) z(:)].');
  fclose (file_id);

endfunction

